language: node_js
node_js:
  - '8'
  - '10'
before_script:
  - npm run lint
install:
  - npm install --ignore-engines
  - npm install -g codecov
script:
  - npm test
  - codecov
after_success:
  - npm run semantic-release
deploy:
  provider: npm
  email: "vlad@durnea.com"
  api_key: "caa21942-8245-4ae9-9e63-1c932e068400"